version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "my-angular-image"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Tagging image...
      - docker tag my-angular-image:latest 804033740036.dkr.ecr.us-east-1.amazonaws.com/my-angular-image:latest
      - echo Pushing image...
      - docker push 804033740036.dkr.ecr.us-east-1.amazonaws.com/my-angular-image:latest

artifacts:
  files:
    - '**/*'
